title: "Pupilist"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: GFM

repository: "AY2223S1-CS2103T-W09-4/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
